const demoFiles = {
  'Beethoven Op53_1': {
    meiFile:
      'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op53_HenleUrtext/master/Beethoven_Op53_1-HenleUrtext.mei',
    performances: {
      '53 P02 Performance A': './maps/Op53_1_P02-A.boe.mid.maps.expansion-default.json',
      '53 P02 Performance B': './maps/Op53_1_P02-B.boe.mid.maps.expansion-default.json',
      '53 P02 Performance C': './maps/Op53_1_P02-C.boe.mid.maps.expansion-default.json',
      '53 P04 Performance A': './maps/Op53_1_P04-A.boe.mid.maps.expansion-default.json',
      '53 P04 Performance B': './maps/Op53_1_P04-B.boe.mid.maps.expansion-default.json',
      '53 P04 Performance C': './maps/Op53_1_P04-C.boe.mid.maps.expansion-default.json',
      '53 P07 Performance A': './maps/Op53_1_P07-A.boe.mid.maps.expansion-default.json',
      '53 P07 Performance B': './maps/Op53_1_P07-B.boe.mid.maps.expansion-default.json',
      '53 P08 Performance A': './maps/Op53_1_P08-A.boe.mid.maps.expansion-default.json',
      '53 P08 Performance B': './maps/Op53_1_P08-B.boe.mid.maps.expansion-default.json',
      '53 P08 Performance C': './maps/Op53_1_P08-C.boe.mid.maps.expansion-default.json',
    },
  },
  'Beethoven Op53_2': {
    meiFile:
      'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op53_HenleUrtext/master/Beethoven_Op53_2-HenleUrtext.mei',
    performances: {
      'P02 Performance A': './maps/Op53_2_P02-A.boe.mid.maps.json',
      'P02 Performance B': './maps/Op53_2_P02-B.boe.mid.maps.json',
      'P02 Performance C': './maps/Op53_2_P02-C.boe.mid.maps.json',
      'P04 Performance A': './maps/Op53_2_P04-A.boe.mid.maps.json',
      'P04 Performance B': './maps/Op53_2_P04-B.boe.mid.maps.json',
      'P04 Performance C': './maps/Op53_2_P04-C.boe.mid.maps.json',
      'P07 Performance A': './maps/Op53_2_P07-A.boe.mid.maps.json',
      'P07 Performance B': './maps/Op53_2_P07-B.boe.mid.maps.json',
      'P07 Performance C': './maps/Op53_2_P07-C.boe.mid.maps.json',
      'P08 Performance A': './maps/Op53_2_P08-A.boe.mid.maps.json',
      'P08 Performance B': './maps/Op53_2_P08-B.boe.mid.maps.json',
      'P08 Performance C': './maps/Op53_2_P08-C.boe.mid.maps.json',
    },
  },
  'Beethoven Op31_No2_2': {
    meiFile:
      'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op31_No2_HenleUrtext/master/Beethoven_Op31_No2_2-HenleUrtext.mei',
    performances: {
      'Op31-No2_2 D1': './maps/REC041_12-19_1133.boe.mid.maps.expansion-default.json',
      'Op31-No2_2 D2': './maps/REC042_12-19_1153.boe.mid.maps.expansion-default.json',
      'Op31-No2_2 D3': './maps/REC043_12-19_1202.boe.mid.maps.expansion-default.json',
      'Op31-No2_2 D4': './maps/REC044_12-19_1210.boe.mid.maps.expansion-default.json',
    },
  },
  'Beethoven Op31_No3_1': {
    meiFile:
      'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op31_No3_HenleUrtext/master/Beethoven_Op31_No3_1-HenleUrtext.mei',
    performances: {
      'Op31-No3_1 P01 Performance A': './maps/Op31_No3_1_P01-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P01 Performance B': './maps/Op31_No3_1_P01-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P01 Performance C': './maps/Op31_No3_1_P01-C.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P05 Performance A': './maps/Op31_No3_1_P05-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P05 Performance B': './maps/Op31_No3_1_P05-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P05 Performance C': './maps/Op31_No3_1_P05-C.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P06 Performance A': './maps/Op31_No3_1_P06-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P06 Performance B': './maps/Op31_No3_1_P06-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_1 P06 Performance C': './maps/Op31_No3_1_P06-C.boe.mid.maps.expansion-default.json',
    },
  },
  'Beethoven Op31_No3_2': {
    meiFile:
      'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op31_No3_HenleUrtext/master/Beethoven_Op31_No3_2-HenleUrtext.mei',
    performances: {
      'Op31-No3_2 P01 Performance A': './maps/Op31_No3_2_P01-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P01 Performance B': './maps/Op31_No3_2_P01-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P01 Performance C': './maps/Op31_No3_2_P01-C.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P05 Performance A': './maps/Op31_No3_2_P05-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P05 Performance B': './maps/Op31_No3_2_P05-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P05 Performance C': './maps/Op31_No3_2_P05-C.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P05 Performance D': './maps/Op31_No3_2_P05-D.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P06 Performance A': './maps/Op31_No3_2_P06-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P06 Performance B': './maps/Op31_No3_2_P06-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_2 P06 Performance C': './maps/Op31_No3_2_P06-C.boe.mid.maps.expansion-default.json',
    },
  },
  'Beethoven Op31_No3_3': {
    meiFile:
      'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op31_No3_HenleUrtext/master/Beethoven_Op31_No3_3-HenleUrtext.mei',
    performances: {
      'Op31-No3_3 P01 Performance A': './maps/Op31_No3_3_P01-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P01 Performance B': './maps/Op31_No3_3_P01-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P01 Performance C': './maps/Op31_No3_3_P01-C.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P05 Performance A': './maps/Op31_No3_3_P05-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P05 Performance B': './maps/Op31_No3_3_P05-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P05 Performance C': './maps/Op31_No3_3_P05-C.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P05 Performance D': './maps/Op31_No3_3_P05-D.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P06 Performance A': './maps/Op31_No3_3_P06-A.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P06 Performance B': './maps/Op31_No3_3_P06-B.boe.mid.maps.expansion-default.json',
      'Op31-No3_3 P06 Performance C': './maps/Op31_No3_3_P06-C.boe.mid.maps.expansion-default.json',
    },
  },
  'Beethoven Op119_No1_1': {
    meiFile:
      'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op119_BreitkopfHaertel/master/Beethoven_Op119_Nr01-Breitkopf.mei',
    performances: {
      '119 Pianist 1': './maps/Beethoven_Op119_1_maps.json',
      '119 Pianist 2': './maps/Beethoven_Op119_1_maps.json',
    },
  },
  'Chopin Op10_No3_1 Etude': {
    meiFile: 'https://raw.githubusercontent.com/wergo/vienna4x22/refs/heads/master/mei/Chopin_Op10_3_1.mei',
    performances: {
      'Pianist 1': './maps/Chopin_op10_no3_p01-mei.maps.json',
      'Pianist 2': './maps/Chopin_op10_no3_p02-mei.maps.json',
      'Pianist 3': './maps/Chopin_op10_no3_p03-mei.maps.json',
      'Pianist 4': './maps/Chopin_op10_no3_p04-mei.maps.json',
      'Pianist 5': './maps/Chopin_op10_no3_p05-mei.maps.json',
      'Pianist 6': './maps/Chopin_op10_no3_p06-mei.maps.json',
      'Pianist 7': './maps/Chopin_op10_no3_p07-mei.maps.json',
      'Pianist 8': './maps/Chopin_op10_no3_p08-mei.maps.json',
      'Pianist 9': './maps/Chopin_op10_no3_p09-mei.maps.json',
      'Pianist 10': './maps/Chopin_op10_no3_p10-mei.maps.json',
      'Pianist 11': './maps/Chopin_op10_no3_p11-mei.maps.json',
      'Pianist 12': './maps/Chopin_op10_no3_p12-mei.maps.json',
      'Pianist 13': './maps/Chopin_op10_no3_p13-mei.maps.json',
      'Pianist 14': './maps/Chopin_op10_no3_p14-mei.maps.json',
      'Pianist 15': './maps/Chopin_op10_no3_p15-mei.maps.json',
      'Pianist 16': './maps/Chopin_op10_no3_p16-mei.maps.json',
      'Pianist 17': './maps/Chopin_op10_no3_p17-mei.maps.json',
      'Pianist 18': './maps/Chopin_op10_no3_p18-mei.maps.json',
      'Pianist 19': './maps/Chopin_op10_no3_p19-mei.maps.json',
      'Pianist 20': './maps/Chopin_op10_no3_p20-mei.maps.json',
      'Pianist 21': './maps/Chopin_op10_no3_p21-mei.maps.json',
      'Pianist 22': './maps/Chopin_op10_no3_p22-mei.maps.json',
    },
  },
  'Chopin Op38 Ballade No. 1': {
    meiFile: 'https://raw.githubusercontent.com/wergo/vienna4x22/refs/heads/master/mei/Chopin_Op38_1.mei',
    performances: {
      'Pianist 1': './maps/Chopin_op38_p01-mei.maps.json',
      'Pianist 2': './maps/Chopin_op38_p02-mei.maps.json',
      'Pianist 3': './maps/Chopin_op38_p03-mei.maps.json',
      'Pianist 4': './maps/Chopin_op38_p04-mei.maps.json',
      'Pianist 5': './maps/Chopin_op38_p05-mei.maps.json',
      'Pianist 6': './maps/Chopin_op38_p06-mei.maps.json',
      'Pianist 7': './maps/Chopin_op38_p07-mei.maps.json',
      'Pianist 8': './maps/Chopin_op38_p08-mei.maps.json',
      'Pianist 9': './maps/Chopin_op38_p09-mei.maps.json',
      'Pianist 10': './maps/Chopin_op38_p10-mei.maps.json',
      'Pianist 11': './maps/Chopin_op38_p11-mei.maps.json',
      'Pianist 12': './maps/Chopin_op38_p12-mei.maps.json',
      'Pianist 13': './maps/Chopin_op38_p13-mei.maps.json',
      'Pianist 14': './maps/Chopin_op38_p14-mei.maps.json',
      'Pianist 15': './maps/Chopin_op38_p15-mei.maps.json',
      'Pianist 16': './maps/Chopin_op38_p16-mei.maps.json',
      'Pianist 17': './maps/Chopin_op38_p17-mei.maps.json',
      'Pianist 18': './maps/Chopin_op38_p18-mei.maps.json',
      'Pianist 19': './maps/Chopin_op38_p19-mei.maps.json',
      'Pianist 20': './maps/Chopin_op38_p20-mei.maps.json',
      'Pianist 21': './maps/Chopin_op38_p21-mei.maps.json',
      'Pianist 22': './maps/Chopin_op38_p22-mei.maps.json',
    },
  },
  'Mozart Sonata K. 331': {
    meiFile: 'https://raw.githubusercontent.com/wergo/vienna4x22/refs/heads/master/mei/Mozart-KV331_1-expanded.mei',
    performances: {
      'Pianist 1': './maps/Mozart_K331_1st-mov_p01-mei.maps.json',
      'Pianist 2': './maps/Mozart_K331_1st-mov_p02-mei.maps.json',
      'Pianist 3': './maps/Mozart_K331_1st-mov_p03-mei.maps.json',
      'Pianist 4': './maps/Mozart_K331_1st-mov_p04-mei.maps.json',
      'Pianist 5': './maps/Mozart_K331_1st-mov_p05-mei.maps.json',
      'Pianist 6': './maps/Mozart_K331_1st-mov_p06-mei.maps.json',
      'Pianist 7': './maps/Mozart_K331_1st-mov_p07-mei.maps.json',
      'Pianist 8': './maps/Mozart_K331_1st-mov_p08-mei.maps.json',
      'Pianist 9': './maps/Mozart_K331_1st-mov_p09-mei.maps.json',
      'Pianist 10': './maps/Mozart_K331_1st-mov_p10-mei.maps.json',
      'Pianist 11': './maps/Mozart_K331_1st-mov_p11-mei.maps.json',
      'Pianist 12': './maps/Mozart_K331_1st-mov_p12-mei.maps.json',
      'Pianist 13': './maps/Mozart_K331_1st-mov_p13-mei.maps.json',
      'Pianist 14': './maps/Mozart_K331_1st-mov_p14-mei.maps.json',
      'Pianist 15': './maps/Mozart_K331_1st-mov_p15-mei.maps.json',
      'Pianist 16': './maps/Mozart_K331_1st-mov_p16-mei.maps.json',
      'Pianist 17': './maps/Mozart_K331_1st-mov_p17-mei.maps.json',
      'Pianist 18': './maps/Mozart_K331_1st-mov_p18-mei.maps.json',
      'Pianist 19': './maps/Mozart_K331_1st-mov_p19-mei.maps.json',
      'Pianist 20': './maps/Mozart_K331_1st-mov_p20-mei.maps.json',
      'Pianist 21': './maps/Mozart_K331_1st-mov_p21-mei.maps.json',
      'Pianist 22': './maps/Mozart_K331_1st-mov_p22-mei.maps.json',
    },
  },
  'Schubert: Deutscher Tanz D.783 No. 15': {
    meiFile: 'https://raw.githubusercontent.com/wergo/vienna4x22/refs/heads/master/mei/Schubert_783_15-expanded.mei',
    performances: {
      'Pianist 1': './maps/Schubert_D783_no15_p01-mei.maps.json',
      'Pianist 2': './maps/Schubert_D783_no15_p02-mei.maps.json',
      'Pianist 3': './maps/Schubert_D783_no15_p03-mei.maps.json',
      'Pianist 4': './maps/Schubert_D783_no15_p04-mei.maps.json',
      'Pianist 5': './maps/Schubert_D783_no15_p05-mei.maps.json',
      'Pianist 6': './maps/Schubert_D783_no15_p06-mei.maps.json',
      'Pianist 7': './maps/Schubert_D783_no15_p07-mei.maps.json',
      'Pianist 8': './maps/Schubert_D783_no15_p08-mei.maps.json',
      'Pianist 9': './maps/Schubert_D783_no15_p09-mei.maps.json',
      'Pianist 10': './maps/Schubert_D783_no15_p10-mei.maps.json',
      'Pianist 11': './maps/Schubert_D783_no15_p11-mei.maps.json',
      'Pianist 12': './maps/Schubert_D783_no15_p12-mei.maps.json',
      'Pianist 13': './maps/Schubert_D783_no15_p13-mei.maps.json',
      'Pianist 14': './maps/Schubert_D783_no15_p14-mei.maps.json',
      'Pianist 15': './maps/Schubert_D783_no15_p15-mei.maps.json',
      'Pianist 16': './maps/Schubert_D783_no15_p16-mei.maps.json',
      'Pianist 17': './maps/Schubert_D783_no15_p17-mei.maps.json',
      'Pianist 18': './maps/Schubert_D783_no15_p18-mei.maps.json',
      'Pianist 19': './maps/Schubert_D783_no15_p19-mei.maps.json',
      'Pianist 20': './maps/Schubert_D783_no15_p20-mei.maps.json',
      'Pianist 21': './maps/Schubert_D783_no15_p21-mei.maps.json',
      'Pianist 22': './maps/Schubert_D783_no15_p22-mei.maps.json',
    },
  },
  'Schumann: Die Kartenlegerin': {
    meiFile:
      'https://raw.githubusercontent.com/TogethernessProject/Schumann_Kartenlegerin/main/Schumann_Op31_No2_Die-Kartenlegerin_Es-Dur_Peters.mei',
    performances: {
      'Duo 1 Round 1': './maps/duo1-PostR-1Schumann.maps.json',
      'Duo 1 Round 2': './maps/duo1-PostR-2Schumann.maps.json',
      'Duo 1 Round 3': './maps/duo1-PostR-3Schumann.maps.json',
      'Duo 2 Pre Rnd': './maps/duo2-PreR-Schumann.maps.json',
      'Duo 2 Round 1': './maps/duo2-PostR-1Schumann.maps.json',
      'Duo 2 Round 2': './maps/duo2-PostR-2Schumann.maps.json',
      'Duo 2 Round 3': './maps/duo2-PostR-3Schumann.maps.json',
    },
  },
  'Fauré: Automne': {
    meiFile:
      'https://raw.githubusercontent.com/TogethernessProject/Faure_Automne/main/Faure_Op18_No3_Automne_h-Moll_Hamelle.mei',
    performances: {
      'Duo 1 Round 2': './maps/duo1-PostR-2Faure.maps.json',
      'Duo 1 Round 3': './maps/duo1-PostR-3Faure.maps.json',
      'Duo 2 Pre Rnd': './maps/duo2-PreR-Faure.maps.json',
      'Duo 2 Round 1': './maps/duo2-PostR-1Faure.maps.json',
      'Duo 2 Round 2': './maps/duo2-PostR-2Faure.maps.json',
      'Duo 2 Round 3': './maps/duo2-PostR-3Faure.maps.json',
    },
  },
};

const defaultPiece = '';
const defaultMapsFileName = '';
const defaultMeiFileName = '';
// const defaultPiece = 'Beethoven Op119_No1_1';
// const defaultMapsFileName = './maps/Beethoven_Op119_1_maps.json';
// const defaultMeiFileName =
//   "https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op119_BreitkopfHaertel/master/Beethoven_Op119_Nr01-Breitkopf.mei";
